name: Generate HTML + Sitemap

on:
  push:
    branches: [main]
    paths:
      - 'markdown/**'   # Nur ausführen, wenn sich Markdown-Dateien ändern

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate HTML from Markdown
        run: node generate-html.js

      - name: Zeige Inhalt von docs/
        run: ls -l docs/

      - name: Zeige Git Status
        run: |
          git status
          git diff --stat

      - name: Generate Index page
        run: node generate-index.js

      - name: Generate sitemap and robots.txt
        run: node generate-sitemap.js

<<<<<<< HEAD
      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/ index.html sitemap.xml robots.txt

          if ! git diff --cached --quiet; then
            git commit -m "🔄 HTML automatisch aus Markdown generiert"
            git push
          else
            echo "✅ Keine Änderungen – nichts zu committen"
=======
    - name: Commit and push generated files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs/ sitemap.xml robots.txt
        git commit -m "🔄 Auto-generated HTML and meta files"
        git push || echo "No changes to commit"
>>>>>>> 4b3389b3efc2ee8ff880848d473be5d5e665b34e
